### ISSUE TITLE
Feature: Make file name length adjustable

### ISSUE THREAD

**Issue by Aybee** [numero2/contao-proper-filenames#1]
Is there a special reason why filenames gets truncated to 32 chars? Can you make this optional or adjustable?

**Comment by bennyborn** [comment]
Actually no, no special reason.

I created this extension to keep people from going wild when naming files since (as you might know, otherwise you would'nt be here) using all sorts of special characters and casing can cause some real trouble on the webserver.

So if I already limit the kind of characters to be used why not limit the filename itself in length?
It surely results in a better readable filename than `thisfileisatotallyawesomeandbecauseofsomereasoniwilltrytomakethefilenameasdescriptiveaspossible.txt`

**Comment by Aybee** [comment]
Yes I know. Thats why I tried your extension. But unfortunately just my very first test comes up with a bad result.
`Trinkwasser Mönchengladbach Windberg.txt`
=>
`trinkwasser-moenchengladbach-win.txt`

So you can see, that its obviously better if it becomes
`trinkwasser-moenchengladbach-windberg.txt`

**Comment by bennyborn** [comment]
Well, for now you could simply set the limit higher in [CheckFilenames.php#L74](https://github.com/numero2/contao-proper-filenames/blob/c1ff1eefea1069caf9f3c6adbd1b1383670f4c33/system/modules/proper-filenames/classes/CheckFilenames.php#L74).
I will try to add a setting to disable to limit as soon I've got some time.

**Comment by Aybee** [comment]
Yes I know where to increase the limit. Thank you for accepting this feature request.

**Comment by Aybee** [comment]
Vielen Dank.
